<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- Target and Build -->
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Publishing -->
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>

    <!-- Optimizations -->
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.Odbc" Version="10.0.5" />
  </ItemGroup>

</Project>
